apiVersion: v1
kind: Service
metadata:
  name: choose-assessment-module
spec:
  selector:
    app: choose-assessment-module
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
